# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='T\xedtulo')),
                ('description', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('slug', models.SlugField(max_length=250, verbose_name='Identificador')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Imagem')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
