# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170126_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
